appcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
  path('', views.Home.as_view(), name='home'),
  path('about/', views.about, name='about'),
  path('applications/', views.app_index, name = 'app-index'),
  path('applications/<int:app_id>/', views.app_detail, name = 'app-detail'),
  path('applications/create/', views.AppCreate.as_view(), name='app-create'),
  path('applications/<int:pk>/update/', views.AppUpdate.as_view(), name='app-update'),
  path('applications/<int:pk>/delete/', views.AppDelete.as_view(), name='app-delete'),
  path('application/<int:app_id>/add-interview/', views.add_interview, name='add-interview'),
  path('coverletters/', views.cl_index, name='cl-index'),
  path('coverletters/<int:cl_id>/', views.cl_detail, name='cl-detail'),
  path('coverletters/create/', views.ClCreate.as_view(), name='cl-create'),
  path('coverletters/<int:pk>/update/', views.ClUpdate.as_view(), name='cl-update'),
  path('coverletters/<int:pk>/delete/', views.ClDelete.as_view(), name='cl-delete'),
  path('coverletters/<int:cl_id>/add-doc/', views.add_doc, name='add-doc'),
  path('accounts/signup/', views.signup, name='signup'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User

SMILES = (
  ('1', '😐 Neutral'), #neutral
  ('2', '😃 Happy '), #happy
  ('3', '😍 Excited'), #very excited
)

ARRANGEMENTS = (
  ('R', 'Remote'),
  ('H', 'Hybrid'),
  ('O', 'On-site'),
)

STATUS = (
  ('A', 'Applied'),
  ('Y', 'Yet to Apply'),
  ('I', 'Interviewing'),
  ('N', 'Negotiating'),
  ('O', 'Accepted'),
  ('D', 'Decline'),
  ('R', 'Rejected'),
)

STATES = (
  ('AL', 'Alabama'),
  ('AK', 'Alaska'),
  ('AZ', 'Arizona'),
  ('AR', 'Arkansas'),
  ('CA', 'California'),
  ('CO', 'Colorado'),
  ('CT', 'Connecticut'),
  ('DE', 'Delaware'),
  ('FL', 'Florida'),
  ('GA', 'Georgia'),
  ('HI', 'Hawaii'),
  ('ID', 'Idaho'),
  ('IL', 'Illinois'),
  ('IN', 'Indiana'),
  ('IA', 'Iowa'),
  ('KS', 'Kansas'),
  ('KY', 'Kentucky'),
  ('LA', 'Louisiana'),
  ('ME', 'Maine'),
  ('MD', 'Maryland'),
  ('MA', 'Massachusetts'),
  ('MI', 'Michigan'),
  ('MN', 'Minnesota'),
  ('MS', 'Mississippi'),
  ('MO', 'Missouri'),
  ('MT', 'Montana'),
  ('NE', 'Nebraska'),
  ('NV', 'Nevada'),
  ('NH', 'New Hampshire'),
  ('NJ', 'New Jersey'),
  ('NM', 'New Mexico'),
  ('NY', 'New York'),
  ('NC', 'North Carolina'),
  ('ND', 'North Dakota'),
  ('OH', 'Ohio'),
  ('OK', 'Oklahoma'),
  ('OR', 'Oregon'),
  ('PA', 'Pennsylvania'),
  ('RI', 'Rhode Island'),
  ('SC', 'South Carolina'),
  ('SD', 'South Dakota'),
  ('TN', 'Tennessee'),
  ('TX', 'Texas'),
  ('UT', 'Utah'),
  ('VT', 'Vermont'),
  ('VA', 'Virginia'),
  ('WA', 'Washington'),
  ('WV', 'West Virginia'),
  ('WI', 'Wisconsin'),
  ('WY', 'Wyoming')
)

TYPES = (
  ('R','Referal'),
  ('C','Company Portal'),
  ('L','LinkedIn'),
  ('M','Monster'),
  ('G','Glassdoor'),
  ('L','LinkUp'),
  ('S','SimplyHired'),
  ('Z','ZipRecruiter'),
  ('I','Indeed'),
)

INTERVIEWTYPES = (
  ('P', 'Phone Screen'),
  ('T', 'Technical'),
  ('C', 'Cultural-Fit'),
  ('O', 'On-Site'),
  ('S', 'System-Design'),
  ('C', 'Code-Review'),
)

# Create your models here.
class Application(models.Model):
  app_date = models.DateField('Application Submission Date', null=False, blank=True)
  position = models.CharField(max_length=100)
  company = models.CharField(max_length=100)
  enthusiasm = models.CharField(max_length=1, choices=SMILES, default=SMILES[0][0] )
  work_arrangement = models.CharField('Work Arrangement', max_length=1, choices=ARRANGEMENTS, default=ARRANGEMENTS[0][0])
  state = models.CharField(max_length=2, choices=STATES, default=STATES[0][0])
  city = models.CharField(max_length=50)
  techstack = models.TextField('Technology Stack', max_length=100)
  status = models.CharField(max_length=1, choices=STATUS, default=STATUS[0][0])
  minsalary = models.DecimalField('Minimum Salary',max_digits=10, decimal_places=2, null=True, blank=True)
  maxsalary = models.DecimalField('Maximum Salary', max_digits=10, decimal_places=2, null=True, blank=True)
  notes = models.TextField(max_length=1000)
  application_type = models.CharField(max_length=1, choices=TYPES, default=TYPES[0][0])
  user = models.ForeignKey(User, on_delete=models.CASCADE)
  
  def __str__(self):
    return self.position
  
  def get_absolute_url(self):
    return reverse('app-detail', kwargs={'app_id': self.id})
  
class Interview(models.Model):
  date = models.DateField('Interview Date', null=False, blank=True)
  interviewType = models.CharField('Interview Type',
    max_length=1,
    choices=INTERVIEWTYPES,
    default=INTERVIEWTYPES[0][0]
  )
  notes = models.TextField(max_length=100, default="")
  app = models.ForeignKey(Application, on_delete=models.CASCADE)

  def __str__(self):
    return f"{self.get_interviewType_display()} on {self.date}"
  
  class Meta: 
    ordering = ['-date']


class CoverLetter(models.Model):
  cl_date = models.DateField('Date', null=False, blank=True)
  position = models.CharField('Title', max_length=50, null=False, blank=True)
  letter = models.TextField('Cover Letter', max_length=2500, null=False, blank=True)
  tags = models.CharField('Tags', max_length=250)
  user = models.ForeignKey(User, on_delete=models.CASCADE)

  def __str__(self):
    return self.position
  
  def get_absolute_url(self):
    return reverse('cl-detail', kwargs={'cl_id': self.id})
  
class Document(models.Model):
  url = models.CharField(max_length=250)
  cl = models.ForeignKey(CoverLetter, on_delete=models.CASCADE)

  def __str__(self):
    return f"Document for cl_id: {self.cl_id} @{self.url}"
  

main_app/forms.py
from django.forms import ModelForm
from .models import Interview

class InterviewForm(ModelForm):
  class Meta:
    model = Interview
    fields = ['date', 'interviewType', 'notes' ]

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from .models import Application, CoverLetter, Document
from .forms import InterviewForm
import uuid
import boto3


S3_BASE_URL = 'https://s3.us-east-1.amazonaws.com/'
BUCKET = 'aryanatts-app-collector'

# Create your views here.
class Home(LoginView):
  template_name = 'home.html'

def signup(request):
  error_message = ''
  if request.method == 'POST':
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      login(request, user)
      return redirect('about')
    else:
      error_message = 'Invalid sign up - try again'
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'signup.html', context)

def about(request):
  return render(request, 'about.html')

@login_required
def app_index(request):
  apps = Application.objects.filter(user=request.user)
  return render(request, 'applications/index.html', { 'apps': apps })

@login_required
def app_detail(request, app_id):
  app = Application.objects.get(id=app_id)
  interview_form = InterviewForm()
  return render(request, 'applications/detail.html', {
    'app' : app,
    'interview_form': interview_form
    })

class AppCreate(LoginRequiredMixin, CreateView):
  model = Application
  fields = ['app_date', 'position', 'company', 'application_type', 'enthusiasm', 'work_arrangement', 'state', 'city', 'techstack', 'status', 'minsalary', 'maxsalary', 'notes']
  success_url = '/applications'
    
  def form_valid(self, form):
    form.instance.user = self.request.user
    return super().form_valid(form)

class AppUpdate(LoginRequiredMixin, UpdateView):
  model = Application
  fields = ['app_date', 'position', 'company', 'application_type', 'enthusiasm', 'work_arrangement', 'state', 'city', 'techstack', 'status', 'minsalary', 'maxsalary', 'notes']

class AppDelete(LoginRequiredMixin, DeleteView):
  model = Application
  success_url = '/applications/'

@login_required
def add_interview(request, app_id):
  form = InterviewForm(request.POST)
  if form.is_valid():
    print("interview is VALIDDD")
    new_interview = form.save(commit=False)
    new_interview.app_id = app_id
    new_interview.save()
  print("interview is INVALIDDD")
  return redirect('app-detail', app_id=app_id)

@login_required
def cl_index(request):
  cls = CoverLetter.objects.filter(user=request.user)
  return render(request, 'coverletters/cl-index.html', { 'cls': cls })

@login_required
def cl_detail(request, cl_id):
  cl = CoverLetter.objects.get(id=cl_id)
  try: 
    doc = Document.objects.get(cl_id=cl_id) #Gives you ONE thing
  except:
    doc = None
  return render(request, 'coverletters/cl-detail.html', {
    'cl' : cl, 
    'doc': doc, 
    })

class ClCreate(LoginRequiredMixin, CreateView):
  model = CoverLetter
  fields = ['cl_date', 'position', 'letter', 'tags']
  success_url = '/coverletters'
    
  def form_valid(self, form):
    form.instance.user = self.request.user
    return super().form_valid(form)

class ClUpdate(LoginRequiredMixin, UpdateView):
  model = CoverLetter
  fields = ['cl_date', 'position', 'letter', 'tags']

class ClDelete(LoginRequiredMixin, DeleteView):
  model = CoverLetter
  success_url = '/coverletters'

@login_required
def add_doc(request, cl_id):
  doc_file = request.FILES.get('doc-file', None)
  if doc_file:
    s3 = boto3.client('s3')
    key = uuid.uuid4().hex + doc_file.name[doc_file.name.rfind('.'):]
    try:
      s3.upload_fileobj(doc_file, BUCKET, key)
      url = f"{S3_BASE_URL}{BUCKET}/{key}"
      document = Document(url=url, cl_id=cl_id)
      cl_document = Document.objects.filter(cl_id=cl_id)
      if cl_document.first():
        cl_document.first().delete()
      document.save()
    except Exception as err:
      print('An error occurred uploading file to S3: %s' % err)
  return redirect('cl-detail', cl_id=cl_id)

main_app/templates/applications/detail.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link 
  href="https://cdn.jsdelivr.net/npm/mc-datepicker/dist/mc-calendar.min.css" 
  rel="stylesheet" 
/>
<link rel="stylesheet" href="{% static 'css/mcdp.css' %}">
<script src="https://cdn.jsdelivr.net/npm/mc-datepicker/dist/mc-calendar.min.js">
</script>
<link 
rel="stylesheet"
type="text/css"
href="{% static 'css/app-detail.css' %}"
/>
<script defer src="{% static 'js/app-detail.js' %}"></script>
{% endblock %}

{% block content %}
<div class="app-container">
  <div class="app-header">
    {{ app.company }} </br>
    {{ app.position }}
    <div class="app-actions">
      <a href="{% url 'app-update' app.id %}" class="btn warn">Edit</a>
      <a href="{% url 'app-delete' app.id %}" class="btn danger">Delete</a>
    </div>
  </div>
  <div class="app-info">
    <table style="width:100%" class="content-table">
      <tr>
        <th>Date Submitted:</th>
        <td>{{ app.app_date }}</td>
      </tr>
      <tr>
        <th>Submission:</th>
        <td>{{ app.get_application_type_display }}</td>
      </tr>
      <tr>
        <th>Location:</th>
        <td>{{ app.city }}, {{ app.state }}</td>
      </tr>
      <tr>
        <th>Status:</th>
        <td>{{ app.get_status_display }}</td>
      </tr>
      <tr>
        <th>Salary Range:</th>
        <td>{{ app.minsalary }} - {{ app.maxsalary }}</td>
      </tr>
      <tr>
        <th>Tech Stack:</th>
        <td>{{ app.techstack }}</td>
      </tr>
    </table>
  </div>
  <h3>Notes</h3>
  <div class="app-notes">
    {{ app.notes }}
  </div>
<div class="interviewsContainer">
  <div class="scheduled-interviews">
    <table class="interview-table">
      <thead>
        <tr><th>Date</th><th>Type</th><th class="cell_note">Notes</th></tr>
      </thead>
      <tbody>
        {% for interview in app.interview_set.all %}
        <tr class="int_rows">
          <td>{{interview.date}}</td>
          <td>{{interview.get_interviewType_display}}</td>
          <td class="cell_note">{{interview.notes}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <div class="new-interview">
    <form
    action="{% url 'add-interview' app.id %}"
    method="post" 
    class="interview-form"
    autocomplete="off"
    >
    {% csrf_token %}
    {{ interview_form.as_p }}
    <button type="submit" class="button-37">Add Interview</button>
    </form>
  </div>
</div>
{% endblock %}

main_app/templates/applications/index.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link 
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/app-index.css' %}"
/>
{% endblock %}

{% block content %}
<section class="card-container">
  <h1>List of all Applications</h1>
  <div class="create-header">
    <a href="{% url 'app-create' %}"><i class="fa-regular fa-square-plus" style="color: #009879"></i> Create New </a>
  </div>
  <div class="dashboard-table">
    <table class="content-table">
      <tr class="headers">
        <th>Position</th>
        <th>Company</th>
        <th>Enthusiasm</th>
        <th>Work Arrangement</th>
        <th>Location </th>
        <th>Tech Stack</th>
        <th>Status</th>
        <th>Min Salary</th>
        <th>Max Salary</th>
      </tr>
      {% if apps %}
        {% for app in apps %}
        <tr class="rows">
          <td><a href="{% url 'app-detail' app.id %}">{{ app.position }}</a></td>
          <td>{{ app.company }}</td>
          <td>{{ app.get_enthusiasm_display }}</td>
          <td>{{ app.get_work_arrangement_display }}</td>
          <td>{{ app.city }}, {{ app.state }}</td>
          <td>{{ app.techstack }}</td>
          <td>{{ app.get_status_display }}</td>
          <td>{{ app.minsalary  }}</td>
          <td>{{ app.maxsalary }}</td>
        </tr>
        {% endfor %}
      {% else %}
        <tr class="rows">
          <td colspan="9">No Applications</td>
        </tr>
      {% endif %}
    <table>
  </div>
</section>

{% endblock %}